Configuration:
  DisablePathCorrection: false
  EnablePathEscape: false
  FireMethodNotAllowed: false
  DisableBodyConsumptionOnUnmarshal: true
  TimeFormat: Mon, 01 Jan 2006 15:04:05 GMT
  Charset: UTF-8

#自定义配置
own:
  separate: false
  port: 7000
  ignore_urls: [/app/user/login, /app/user/logout,/app/system/info,/app/host/slaveHealth,/app/appVersion/doJobHook,/app/appVersion/payload,/app/firewall/saveWafAccessLog,/app/firewall/loadIps,/app/firewall/getFirewallRulesByHost]
  jwt_timeout: 120 #minute
  log_level: debug
  secret: xxx-Secret
  websocket_pool: 100
  domain: a
  kafka_ip: 192.168.1.101
  kafka_port: 9092
  kafka_group: zihaoGroupId
  kafka_topic: zihaoTopic,logTrace
  kafka_switch: OFF
  db: sqlite # mysql
  cache: local # redis
  data_path: /Users/wuxuewen
  container_scheduling: default  # k8s
  sqlite_path: ./db/zihao.db
  ip_data: ./conf/qqwry.dat
  qqwry_url: "http://update.cz88.net/ip/qqwry.rar"
  server_ip_url: "http://ip.dhcp.cn/?ip"
  guacad_addr: "127.0.0.1:4822"
#  sqlite_path: D:\\hc\\db\\zihao.db
#  sqlite_path: /Users/wuxuewen/project/go/db/zihao.db